language: csharp
solution: SGCOS.sln
install:
  - nuget restore SGCOS.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Debug SGCOS.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./NUnitTestSGCOS.csproj/bin/Debug/NUnitTestSGCOS.Tests.dll
