dist : xenial
addons :
  snaps :
  - nome : dotnet-sdk
    clássico : true
    canal : latest / beta
sudo : obrigatório
linguagem : csharp
mono : nenhum
roteiro :
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet --version