dist: xenial
language: csharp
solution: SGCOS.sln
mono: none
sudo: required
dotnet: 2.2.203
stages:
  - build
jobs:
  include:
    - stage: build
      name: build solution
      script: dotnet restore && dotnet build